Repository statechannels/statechannels, pull requests merged in 2020-10, with the labels that each got.

#2690 [server-wallet] Fix skipped tests
  packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts
Labels: :carrot: conventional

#2670 [server-wallet] Add 'Unfunded' funding strategy support
  packages/server-wallet/src/__test__/create-and-close-channel/fake-funding.test.ts
  packages/server-wallet/src/protocols/application.ts
  packages/server-wallet/src/wallet/store.ts
Labels: :carrot: conventional, server-wallet

#2691 docs: increase clarity around calldata (forceMove)
  packages/docs-website/docs/protocol-tutorial/finalize-a-channel-sad.md
  packages/nitro-protocol/contracts/ForceMove.sol
Labels: :carrot: conventional

#2695 Clean up some TODOs in Join Channel tests
  packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts
Labels: :carrot: conventional

#2697 Remove obsolete todo
  packages/server-wallet/e2e-test/e2e.test.ts
Labels: :carrot: conventional

#2696 Stop using constant network id
  packages/server-wallet/src/wallet/index.ts
Labels: :carrot: conventional

#2698 refactor: remove db-admin knex and truncate method
  packages/server-wallet/benchmarks/get-channel.benchmark.ts
  packages/server-wallet/benchmarks/update-channel.benchmark.ts
  packages/server-wallet/e2e-test/e2e.test.ts
  packages/server-wallet/e2e-test/scripts/generate-profile-data.ts
  packages/server-wallet/e2e-test/scripts/stress-test.ts
  packages/server-wallet/jest/knex-setup-teardown.ts
  packages/server-wallet/src/db-admin/db-admin-connection.ts
  packages/server-wallet/src/db-admin/db-admin.ts
  packages/server-wallet/src/db/seeds/1_signing_wallet_seeds.ts
  packages/server-wallet/src/index.ts
  packages/server-wallet/src/models/__test__/app-bytecode.test.ts
  packages/server-wallet/src/wallet/__test__/get-first-participant.test.ts
  packages/server-wallet/src/wallet/__test__/integration/close-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/create-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts
  packages/server-wallet/src/wallet/__test__/integration/sync-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/update-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/update-funding.test.ts
  packages/server-wallet/src/wallet/__test__/lock-app.test.ts
  packages/server-wallet/src/wallet/__test__/signing-address.test.ts
Labels: :carrot: conventional

#2700 Fix some VS Code configurations
  .vscode/launch.json
  .vscode/settings.json
Labels: :carrot: conventional

#2702 refactor: log level of debug for mock chain service warning
  packages/server-wallet/src/wallet/index.ts
  yarn.lock
Labels: :carrot: conventional

#2701 [nitro-protocol] Enhance testing of ERC20 deposits and withdrawals
  packages/nitro-protocol/contracts/test/TestErc20AssetHolder.sol
  packages/nitro-protocol/test/contracts/ERC20AssetHolder/deposit.test.ts
  packages/nitro-protocol/test/contracts/NitroAdjudicator/concludePushOutcomeAndTransferAll.test.ts
  packages/nitro-protocol/test/contracts/NitroAdjudicator/pushOutcomeAndTransferAll.test.ts
Labels: :carrot: conventional

#2703 Store objectives in the DB and introduce crash tolerance test
  packages/server-wallet/src/__test__/crash-tolerance/crash-tolerance.seqdiag
  packages/server-wallet/src/__test__/crash-tolerance/crash-tolerance.test.ts
  packages/server-wallet/src/__test__/create-and-close-channel/fake-funding.test.ts
  packages/server-wallet/src/db-admin/db-admin.ts
  packages/server-wallet/src/db/migrations/20201014174039_objectives.ts
  packages/server-wallet/src/models/objective.ts
  packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts
  packages/server-wallet/src/wallet/__test__/integration/update-funding.test.ts
  packages/server-wallet/src/wallet/index.ts
  packages/server-wallet/src/wallet/store.ts
  packages/wallet-core/src/types.ts
  packages/wire-format/src/generated-schema.json
  packages/wire-format/src/types.ts
Labels: :carrot: conventional

#2706 Hardcode migrations paths in admin migrateDB
  packages/server-wallet/src/db-admin/db-admin.ts
Labels: :carrot: conventional

#2710 chore: remove "conflicting" dev dependency
  packages/iframe-channel-provider/package.json
Labels: :carrot: conventional

#2716 docs: fix link in readme
  readme.md
Labels: :carrot: conventional

#2712 chore: disable server-wallet-profiling step
  .circleci/config.yml
Labels: :carrot: conventional

#2714 fix: enter run loop once for joinChannels API call
  packages/server-wallet/src/wallet/index.ts
Labels: :carrot: conventional

#2709 [server-wallet] Ensure Nonce gets bumped on reception of new signed states
  packages/server-wallet/src/models/__test__/nonces.test.ts
  packages/server-wallet/src/models/nonce.ts
  packages/server-wallet/src/wallet/store.ts
Labels: :carrot: conventional, do not merge

#2722 [monorepo] Tweaks to circle config
  .circleci/config.yml
Labels: :carrot: conventional

#2725 fix: db-admin truncates all tables by default
  packages/server-wallet/src/db-admin/db-admin.ts
  packages/server-wallet/src/index.ts
Labels: :carrot: conventional

#2728 fix: log error on invalid state transition of received state instead of throwing
  packages/server-wallet/src/wallet/store.ts
Labels: :carrot: conventional

#2718 refactor: simplify close channel logic
  packages/server-wallet/src/protocols/close-channel.ts
Labels: :carrot: conventional

#2736 refactor: rename onHoldingUpdated to holdingUpdated, singleChannelOutput event to channelUpdate
  packages/server-wallet/src/__chain-test__/direct-funding.test.ts
  packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts
  packages/server-wallet/src/chain-service/chain-service.ts
  packages/server-wallet/src/wallet/index.ts
Labels: :carrot: conventional

#2719 refactor: add support for requesting too much funds from ledger channel
  packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts
  packages/server-wallet/src/models/ledger-requests.ts
  packages/server-wallet/src/protocols/actions.ts
  packages/server-wallet/src/protocols/process-ledger-queue.ts
  packages/server-wallet/src/wallet/index.ts
  packages/server-wallet/src/wallet/store.ts
Labels: :carrot: conventional, server-wallet

#2737 Fix EVM Transition check
  packages/server-wallet/src/__test__/evm-validator.test.ts
  packages/server-wallet/src/models/__test__/fixtures/app-bytecode.ts
  packages/server-wallet/src/wallet/__test__/integration/update-channel.test.ts
  packages/server-wallet/src/wallet/store.ts
Labels: :carrot: conventional

#2744 refactor: remove unused createChannelInternal method
  packages/server-wallet/src/wallet/index.ts
Labels: :carrot: conventional

#2747 refactor: encapsulate ObjectiveModel inside Store
  packages/server-wallet/src/wallet/index.ts
  packages/server-wallet/src/wallet/store.ts
Labels: :carrot: conventional

#2746 refactor: encapsulate AppBytecode inside Store
  packages/server-wallet/src/wallet/index.ts
  packages/server-wallet/src/wallet/store.ts
Labels: :carrot: conventional

#2754 Add networkChainId to store
  packages/server-wallet/src/wallet/__test__/add-my-state.test.ts
  packages/server-wallet/src/wallet/__test__/add-signed-state.test.ts
  packages/server-wallet/src/wallet/__test__/get-first-participant.test.ts
  packages/server-wallet/src/wallet/__test__/lock-app.test.ts
  packages/server-wallet/src/wallet/__test__/sign-state.test.ts
  packages/server-wallet/src/wallet/__test__/signing-address.test.ts
  packages/server-wallet/src/wallet/index.ts
  packages/server-wallet/src/wallet/store.ts
Labels: :carrot: conventional

#2763 fix: only validate new states
  packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts
  packages/server-wallet/src/wallet/store.ts
Labels: :carrot: conventional

#2767 ci: bump canary publish cache
  .github/workflows/publish-canary.yml
Labels: :carrot: conventional

#2771 Use connext version of pure evm
  packages/server-wallet/package.json
  packages/server-wallet/src/evm-validator.ts
  yarn.lock
Labels: :carrot: conventional

#2769 ci: use git diff --exit-code in GH actions
  .github/workflows/publish-canary.yml
  .github/workflows/publish.yml
Labels: :carrot: conventional

#2730 Toughen up crashes (ledger funding test)
  packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts
Labels: :carrot: conventional

#2775 [docs-website] fix: typos
  packages/docs-website/docs/implementation-notes/force-move.md
  packages/docs-website/docs/protocol-tutorial/understand-channel-storage.md
Labels: :carrot: conventional

#2776 chore: add new database indexes for channels table
  packages/server-wallet/src/db/migrations/20201027090001_channels_indexes.ts
Labels: :carrot: conventional

#2777 feat: enhanced getLedgerChannels API with assetHolder and participants query args
  packages/server-wallet/src/models/channel.ts
  packages/server-wallet/src/wallet/index.ts
  packages/server-wallet/src/wallet/store.ts
Labels: :carrot: conventional

#2782 ci: bump cache key
  .circleci/config.yml
Labels: :carrot: conventional

#2770 refactor: do not bind class methods
  packages/server-wallet/src/wallet/index.ts
Labels: :carrot: conventional

#2783 refactor: rename Unfunded -> Fake funding
  packages/client-api-schema/client-api-schema.api.md
  packages/client-api-schema/src/generated-schema.json
  packages/client-api-schema/src/methods/CreateChannel.ts
  packages/server-wallet/src/__test__/create-and-close-channel/fake-funding.test.ts
  packages/server-wallet/src/protocols/__test__/close-channel.test.ts
  packages/server-wallet/src/protocols/close-channel.ts
  packages/server-wallet/src/protocols/open-channel.ts
  packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts
  packages/server-wallet/src/wallet/index.ts
  packages/server-wallet/src/wallet/store.ts
  packages/wire-format/src/generated-schema.json
  packages/wire-format/src/types.ts
  packages/xstate-wallet/src/messaging.ts
Labels: :carrot: conventional

#2788 Fix: Do not evm validate final states
  packages/server-wallet/src/wallet/store.ts
Labels: :carrot: conventional

#2787 Minor fix to use the same alreadyHaveState check when validating transitions
  packages/server-wallet/src/wallet/store.ts
Labels: :carrot: conventional
