Repository statechannels/statechannels, pull requests merged in 2020-11, with the labels that each got.

#2794 fix: change status of unsupported postfund to 'opening'
  packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts
  packages/server-wallet/src/__test__/crash-tolerance/crash-tolerance.test.ts
  packages/server-wallet/src/__test__/create-and-close-channel/direct-funding.test.ts
  packages/server-wallet/src/__test__/create-and-close-channel/fake-funding.test.ts
  packages/server-wallet/src/protocols/state.ts
Labels: :carrot: conventional

#2795 refactor: remove unused join-channel handler
  packages/server-wallet/src/handlers/__test__/join-channel.test.ts
  packages/server-wallet/src/handlers/join-channel.ts
Labels: :carrot: conventional

#2796 refactor: remove unused close-channel handler code
  packages/server-wallet/src/handlers/__test__/close-channel.test.ts
  packages/server-wallet/src/handlers/close-channel.ts
  packages/server-wallet/src/wallet/index.ts
Labels: :carrot: conventional

#2805 fix: remove subtely introduced additional JS ecrecover call (via deserialization fn)
  packages/server-wallet/src/wallet/store.ts
Labels: :carrot: conventional

#2802 chore: remove duplicate implementation of stateWithHashSignedBy
  packages/server-wallet/src/wallet/__test__/add-my-state.test.ts
  packages/server-wallet/src/wallet/__test__/fixtures/states.ts
  packages/server-wallet/src/wallet/__test__/integration/close-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts
  packages/server-wallet/src/wallet/__test__/integration/sync-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/update-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/update-funding.test.ts
  packages/server-wallet/src/wallet/__test__/sign-state.test.ts
Labels: :carrot: conventional

#2807 refactor: de-couple outgoing messages from Store
  packages/server-wallet/src/wallet/index.ts
  packages/server-wallet/src/wallet/store.ts
Labels: :carrot: conventional

#2806 refactor: de-couple state transition validation from store and DB
  packages/server-wallet/src/__test__/evm-validator.test.ts
  packages/server-wallet/src/evm-validator.ts
  packages/server-wallet/src/utilities/validate-transition.ts
  packages/server-wallet/src/wallet/store.ts
Labels: :carrot: conventional

#2800 [server-wallet] Clean store.ts
  packages/server-wallet/src/models/channel.ts
  packages/server-wallet/src/models/nonce.ts
  packages/server-wallet/src/wallet/__test__/add-signed-state.test.ts
  packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts
  packages/server-wallet/src/wallet/store.ts
Labels: :carrot: conventional

#2808 fix: use client-api-schema Participant for public API method
  packages/server-wallet/src/wallet/index.ts
Labels: :carrot: conventional

#2809 fix: fix broken query on ledger channels in DB
  packages/server-wallet/src/models/channel.ts
  packages/server-wallet/src/wallet/__test__/fixtures/create-channel.ts
  packages/server-wallet/src/wallet/__test__/integration/create-ledger-channel.test.ts
  packages/server-wallet/src/wallet/store.ts
Labels: :carrot: conventional

#2811 fix: ensure pushMessage returns latest channelResults
  packages/server-wallet/src/wallet/index.ts
Labels: :carrot: conventional

#2817 Add register byte code method
  packages/server-wallet/src/wallet/index.ts
Labels: :carrot: conventional

#2818 refactor: only process ledgers related to arguments to takeActions
  packages/server-wallet/src/wallet/index.ts
Labels: :carrot: conventional

#2821 ci: don't cache node_modules on the publish workflows
  .github/workflows/publish-canary.yml
  .github/workflows/publish.yml
Labels: :carrot: conventional

#2825 fix: only crank channels related to those in the arguments to crankUntilIdle
  packages/server-wallet/src/wallet/index.ts
Labels: :carrot: conventional

#2824 ci: remove race condition in prepare step
  packages/nitro-protocol/package.json
Labels: :carrot: conventional

#2727 [nitro-protocol] post-audit changes
  .circleci/Dockerfile
  .circleci/config.yml
  packages/devtools/package.json
  packages/docs-website/docs/protocol-tutorial/clear-a-challenge.md
  packages/docs-website/docs/protocol-tutorial/finalize-a-channel-sad.md
  packages/jest-gas-reporter/package.json
  packages/nitro-protocol/bin/compile.js
  packages/nitro-protocol/contracts/AssetHolder.sol
  packages/nitro-protocol/contracts/CountingApp.sol
  packages/nitro-protocol/contracts/ERC20AssetHolder.sol
  packages/nitro-protocol/contracts/ETHAssetHolder.sol
  packages/nitro-protocol/contracts/ForceMove.sol
  packages/nitro-protocol/contracts/NitroAdjudicator.sol
  packages/nitro-protocol/contracts/Outcome.sol
  packages/nitro-protocol/contracts/Token.sol
  packages/nitro-protocol/contracts/TrivialApp.sol
  packages/nitro-protocol/contracts/examples/SingleAssetPayments.sol
  packages/nitro-protocol/contracts/interfaces/Adjudicator.sol
  packages/nitro-protocol/contracts/interfaces/ForceMoveApp.sol
  packages/nitro-protocol/contracts/interfaces/IAssetHolder.sol
  packages/nitro-protocol/contracts/interfaces/IForceMove.sol
  packages/nitro-protocol/contracts/test/TESTAssetHolder.sol
  packages/nitro-protocol/contracts/test/TESTAssetHolder2.sol
  packages/nitro-protocol/contracts/test/TESTForceMove.sol
  packages/nitro-protocol/contracts/test/TESTNitroAdjudicator.sol
  packages/nitro-protocol/contracts/test/TestErc20AssetHolder.sol
  packages/nitro-protocol/contracts/test/TestEthAssetHolder.sol
  packages/nitro-protocol/package.json
  packages/nitro-protocol/src/contract/transaction-creators/force-move.ts
  packages/nitro-protocol/src/transactions.ts
  packages/nitro-protocol/test/contracts/ForceMove/challenge.test..ts
  packages/nitro-protocol/test/contracts/ForceMove/conclude.test.ts
  packages/nitro-protocol/waffle.js
  yarn.lock
Labels: :carrot: conventional

#2829 chore: upgrade api-extractor
  packages/channel-client/package.json
  packages/client-api-schema/client-api-schema.api.md
  packages/client-api-schema/package.json
  packages/iframe-channel-provider/package.json
  yarn.lock
Labels: :carrot: conventional

#2833 refactor: snake case all migrations
  packages/server-wallet/src/db/migrations/20201027090000_chain_service_constraint.ts
Labels: :carrot: conventional

#2834 refactor: restrict objective type to those we currently support
  packages/server-wallet/src/models/objective.ts
Labels: :carrot: conventional

#2828 refactor: remove many SafeMath.add()
  packages/nitro-protocol/contracts/AssetHolder.sol
Labels: :carrot: conventional

#2832 style: remove eslint rule disabling and add type information to utils
  packages/nitro-protocol/.eslintrc.js
  packages/nitro-protocol/src/contract/challenge.ts
  packages/nitro-protocol/src/contract/channel-storage.ts
  packages/nitro-protocol/src/hex-utils.ts
  packages/nitro-protocol/src/signatures.ts
  packages/nitro-protocol/src/transactions.ts
  packages/nitro-protocol/test/test-helpers.ts
  packages/wallet-core/.eslintrc.js
  packages/wallet-core/src/bignumber.ts
  packages/wallet-core/src/serde/wire-format/deserialize.ts
  packages/wallet-core/src/state-utils.ts
  packages/wallet-core/src/utils/helpers.ts
Labels: :carrot: conventional

#2830 feat: add syncChannels API method handler on server-wallet
  packages/server-wallet/src/wallet/index.ts
Labels: :carrot: conventional

#2836 docs: simply quote solidity for channel modes
  packages/docs-website/docs/implementation-notes/force-move.md
  packages/docs-website/docs/protocol-tutorial/understand-channel-storage.md
Labels: :carrot: conventional

#2843 ci: pin to exact versions when canary publishing
  .github/workflows/publish-canary.yml
Labels: :carrot: conventional

#2837 test: anticipate race condition
  packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts
Labels: :carrot: conventional

#2849 Add workaround for noisy log message
  packages/server-wallet/src/utilities/validate-transition.ts
Labels: :carrot: conventional

#2858 fix: remove unnecessary list reversal
  packages/server-wallet/src/utilities/messaging.ts
Labels: :carrot: conventional

#2841 fix: don't throw an error on closeChannels call with empty array
  packages/server-wallet/src/wallet/wallet.ts
Labels: :carrot: conventional

#2854 fix: ensure check on closeChannel in pushMessage
  packages/server-wallet/src/utilities/helpers.ts
  packages/server-wallet/src/wallet/store.ts
  packages/wallet-core/src/types.ts
Labels: :carrot: conventional

#2868 Mark _transferAsset as virtual
  packages/nitro-protocol/contracts/ERC20AssetHolder.sol
Labels: :carrot: conventional

#2869 feat: add addSigningKey method to wallet API
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/wallet/store.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: :carrot: conventional

#2881 build: run yarn
  yarn.lock
Labels: :carrot: conventional

#2890 build: remove unused script and file
  packages/server-wallet/package.json
  packages/server-wallet/scripts/start-dev-server.ts
Labels: :carrot: conventional

#2894 fix: upgrade knex to 0.21.x
  packages/server-wallet/package.json
  yarn.lock
Labels: :carrot: conventional

#2892 ci: remove ci jobs related to hub code
  .circleci/config.yml
Labels: :carrot: conventional

#2884 fix: log failed signState attempt
  packages/server-wallet/src/wallet/wallet.ts
Labels: :carrot: conventional

#2879 refactor: remove usage of DB model in wallet API handler
  packages/server-wallet/src/wallet/store.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: :carrot: conventional

#2887 fix: remove store.destroy method
  packages/server-wallet/src/wallet/store.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: :carrot: conventional

#2888 chore: mark some wallet methods as private
  packages/server-wallet/src/wallet/wallet.ts
Labels: :carrot: conventional

#2889 chore: add sync and async timer for performance metrics
  packages/server-wallet/src/__test__/evm-validator.test.ts
  packages/server-wallet/src/evm-validator.ts
  packages/server-wallet/src/metrics.ts
  packages/server-wallet/src/utilities/validate-transition.ts
  packages/server-wallet/src/wallet/multi-threaded-wallet/worker.ts
  packages/server-wallet/src/wallet/store.ts
Labels: :carrot: conventional

#2891 build: remove netlify CLI from node_modules and related scripts
  .circleci/config.yml
  netlify.toml
  package.json
  packages/docs-website/package.json
  yarn.lock
Labels: :carrot: conventional

#2902 chore: Remove solc
  packages/devtools/package.json
  packages/jest-gas-reporter/package.json
  packages/nitro-protocol/package.json
  yarn.lock
Labels: :carrot: conventional

#2906 Await registerChannelWithChainService
  packages/server-wallet/src/wallet/wallet.ts
Labels: :carrot: conventional

#2907 build: do not use npm-run-all
  packages/nitro-protocol/package.json
Labels: :carrot: conventional

#2909 Revert to published versions
  packages/devtools/package.json
  packages/jest-gas-reporter/package.json
  packages/nitro-protocol/package.json
  packages/server-wallet/package.json
  packages/wallet-core/package.json
  packages/wire-format/package.json
Labels: :carrot: conventional

#2913 test: increase number of tokens minted in Token.sol contract
  packages/nitro-protocol/contracts/Token.sol
Labels: :carrot: conventional

#2915 docs: add precautions section
  packages/docs-website/docs/protocol-tutorial/execute-state-transitions.md
Labels: :carrot: conventional, audit

#2916 Do not allow non variable data in the db
  packages/server-wallet/src/models/__test__/channel.test.ts
  packages/server-wallet/src/models/channel.ts
  packages/server-wallet/src/wallet/__test__/integration/close-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/sync-channel.test.ts
Labels: :carrot: conventional

#2920 fix: add missing dependency to package.json of server-wallet
  packages/server-wallet/package.json
Labels: :carrot: conventional

#2923 feat: emit AssetTransferred for internal transfers
  packages/nitro-protocol/contracts/AssetHolder.sol
  packages/nitro-protocol/contracts/ERC20AssetHolder.sol
  packages/nitro-protocol/contracts/ETHAssetHolder.sol
  packages/nitro-protocol/contracts/Token.sol
  packages/nitro-protocol/contracts/interfaces/IAssetHolder.sol
  packages/nitro-protocol/test/contracts/AssetHolder/claimAll.test.ts
  packages/nitro-protocol/test/contracts/AssetHolder/transfer.test.ts
  packages/nitro-protocol/test/contracts/AssetHolder/transferAll.test.ts
Labels: :carrot: conventional

#2885 Remove one query from the critical path
  packages/server-wallet/src/models/__test__/fixtures/channel.ts
  packages/server-wallet/src/objectives/objective-manager.ts
  packages/server-wallet/src/wallet/__test__/lock-app.test.ts
  packages/server-wallet/src/wallet/__test__/sign-state.test.ts
  packages/server-wallet/src/wallet/store.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: :carrot: conventional

#2930 build: upgrade typescript to 4.1.2
  packages/client-api-schema/package.json
  packages/devtools/package.json
  packages/devtools/src/ganache/deployer-with-cache.ts
  packages/jest-gas-reporter/package.json
  packages/nitro-protocol/package.json
  packages/server-wallet/package.json
  packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts
  packages/wallet-core/package.json
  packages/wire-format/package.json
  yarn.lock
Labels: :carrot: conventional

#2924 feat: catch external destination collisions
  packages/nitro-protocol/src/contract/channel.ts
  packages/nitro-protocol/test/src/contract/external-destination.test.ts
Labels: :carrot: conventional, audit

#2925 fix: require addresses returned from ecrecover to be nonzero
  packages/docs-website/docs/protocol-tutorial/execute-state-transitions.md
  packages/nitro-protocol/contracts/ForceMove.sol
  packages/nitro-protocol/src/contract/transaction-creators/revert-reasons.ts
  packages/nitro-protocol/test/contracts/ForceMove/challenge.test.ts
Labels: :carrot: conventional, audit

#2948 style: unignore and rerun prettier
  packages/nitro-protocol/.prettierignore
  packages/nitro-protocol/contracts/AssetHolder.sol
Labels: :carrot: conventional

#2952 fix: remove unused stateChannelPrivateKey config entry
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/config.ts
Labels: :carrot: conventional

#2949 Refactor Server Wallet Config
  packages/server-wallet/deployment/deploy.ts
  packages/server-wallet/e2e-test/e2e-utils.ts
  packages/server-wallet/e2e-test/payer/client.ts
  packages/server-wallet/e2e-test/payer/start.ts
  packages/server-wallet/e2e-test/receiver/controller.ts
  packages/server-wallet/jest/knex-setup-teardown.ts
  packages/server-wallet/package.json
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts
  packages/server-wallet/src/__test__/crash-tolerance/crash-tolerance.test.ts
  packages/server-wallet/src/__test__/create-and-close-channel/direct-funding.test.ts
  packages/server-wallet/src/__test__/create-and-close-channel/fake-funding.test.ts
  packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts
  packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts
  packages/server-wallet/src/chain-service/__chain-test__/stress.test.ts
  packages/server-wallet/src/config.ts
  packages/server-wallet/src/config/defaults.ts
  packages/server-wallet/src/config/index.ts
  packages/server-wallet/src/config/types.ts
  packages/server-wallet/src/config/utils.ts
  packages/server-wallet/src/db-admin/db-admin.ts
  packages/server-wallet/src/db-admin/knexfile.ts
  packages/server-wallet/src/evm-validator.ts
  packages/server-wallet/src/logger.ts
  packages/server-wallet/src/utilities/__test__/signatures.test.ts
  packages/server-wallet/src/utilities/validate-transition.ts
  packages/server-wallet/src/wallet/__test__/add-my-state.test.ts
  packages/server-wallet/src/wallet/__test__/add-signed-state.test.ts
  packages/server-wallet/src/wallet/__test__/fixtures/utils.ts
  packages/server-wallet/src/wallet/__test__/get-first-participant.test.ts
  packages/server-wallet/src/wallet/__test__/integration/close-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/create-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/create-ledger-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts
  packages/server-wallet/src/wallet/__test__/integration/sync-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/update-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/update-funding.test.ts
  packages/server-wallet/src/wallet/__test__/lock-app.test.ts
  packages/server-wallet/src/wallet/__test__/sign-state.test.ts
  packages/server-wallet/src/wallet/__test__/signing-address.test.ts
  packages/server-wallet/src/wallet/__test__/validate-transition.test.ts
  packages/server-wallet/src/wallet/index.ts
  packages/server-wallet/src/wallet/multi-threaded-wallet/index.ts
  packages/server-wallet/src/wallet/multi-threaded-wallet/manager.ts
  packages/server-wallet/src/wallet/multi-threaded-wallet/worker.ts
  packages/server-wallet/src/wallet/store.ts
  packages/server-wallet/src/wallet/wallet.ts
  yarn.lock
Labels: :carrot: conventional

#2957 ci: invalidate cache
  .circleci/config.yml
Labels: :carrot: conventional

#2963 chore: rename force move to challenge
  packages/nitro-protocol/test/src/transactions.test.ts
Labels: :carrot: conventional

#2967 style: use type system in parameters
  packages/nitro-protocol/contracts/ERC20AssetHolder.sol
  packages/nitro-protocol/contracts/test/TestErc20AssetHolder.sol
Labels: :carrot: conventional, audit

#2973 Config clean up
  packages/server-wallet/src/config/defaults.ts
  packages/server-wallet/src/config/types.ts
  packages/server-wallet/src/config/utils.ts
  packages/server-wallet/src/wallet/index.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: :carrot: conventional

#2976 test: fix ledger funding test to not do unnecesssary check on fundingStatus
  packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts
Labels: :carrot: conventional

#2978 ci: swap carrot for memo
  .github/workflows/commitlint.yml
Labels: :memo: conventional

#2980 refactor: reuse _conclude in concludePush...All
  packages/nitro-protocol/contracts/ForceMove.sol
  packages/nitro-protocol/contracts/NitroAdjudicator.sol
  packages/nitro-protocol/test/contracts/ForceMove/conclude.test.ts
Labels: :memo: conventional, audit

#2977 build: bump jest and ts-jest versions
  packages/client-api-schema/package.json
  packages/devtools/package.json
  packages/nitro-protocol/package.json
  packages/server-wallet/package.json
  packages/wallet-core/package.json
  packages/wire-format/package.json
  yarn.lock
Labels: :carrot: conventional

#2972 test: add off-chain tests against max outcome size, and on-chain test for challenging with max outcome size
  packages/nitro-protocol/src/contract/outcome.ts
  packages/nitro-protocol/src/transactions.ts
  packages/nitro-protocol/test/contracts/ForceMove/challenge.test.ts
  packages/nitro-protocol/test/contracts/NitroAdjudicator/pushOutcome.test.ts
  packages/nitro-protocol/test/src/transactions.test.ts
  packages/nitro-protocol/test/test-helpers.ts
Labels: :carrot: conventional, :memo: conventional

#2982 fix: use hexZeroPad to normalize string as bytes32 versus BigNumber.from
  packages/nitro-protocol/src/contract/asset-holder.ts
  packages/nitro-protocol/test/src/contract/asset-holder.test.ts
Labels: :memo: conventional

#2985 perf: enable solidity compiler optimization
  packages/nitro-protocol/hardhat.config.ts
Labels: :memo: conventional
