Repository statechannels/statechannels, pull requests merged in 2020-12, with the labels that each got.

#2981 fix: improve semantic meaning of input parameters via runtime validation
  packages/docs-website/docs/protocol-tutorial/execute-state-transitions.md
  packages/nitro-protocol/contracts/ForceMove.sol
  packages/nitro-protocol/test/contracts/ForceMove/conclude.test.ts
  packages/nitro-protocol/test/contracts/ForceMove/requireValidInput.test.ts
Labels: :memo: conventional, audit

#2984 emit finalizesAt in Conclude event
  packages/nitro-protocol/contracts/ForceMove.sol
  packages/nitro-protocol/contracts/interfaces/IForceMove.sol
  packages/nitro-protocol/src/contract/transaction-creators/nitro-adjudicator.ts
  packages/nitro-protocol/test/contracts/ForceMove/conclude.test.ts
  packages/nitro-protocol/test/contracts/NitroAdjudicator/pushOutcome.test.ts
Labels: :memo: conventional

#2955 perf: remove unecessary abi.encode
  packages/nitro-protocol/contracts/CountingApp.sol
  packages/nitro-protocol/contracts/ForceMove.sol
  packages/nitro-protocol/contracts/NitroAdjudicator.sol
  packages/nitro-protocol/src/contract/outcome.ts
  packages/server-wallet/package.json
  packages/server-wallet/src/models/__test__/signing-wallet.test.ts
  packages/wallet-core/src/serde/wire-format/example.ts
  yarn.lock
Labels: :carrot: conventional, :memo: conventional, audit

#2998 chore: add hardhat-watcher
  packages/nitro-protocol/hardhat.config.ts
  packages/nitro-protocol/package.json
  yarn.lock
Labels: :memo: conventional

#3002 fix: do not do turn number check for funding or closing stage channels
  packages/server-wallet/src/utilities/validate-transition.ts
Labels: :memo: conventional

#3003 test: record gas consumption in transfer
  packages/nitro-protocol/test/contracts/AssetHolder/transfer.test.ts
Labels: :memo: conventional

#2971 Remove configuration by env var
  .circleci/config.yml
  packages/server-wallet/.env
  packages/server-wallet/.env.development
  packages/server-wallet/.env.test
  packages/server-wallet/.eslintrc.js
  packages/server-wallet/.vscode/launch.json
  packages/server-wallet/deployment/deploy.ts
  packages/server-wallet/e2e-test/e2e-utils.ts
  packages/server-wallet/e2e-test/payer/start.ts
  packages/server-wallet/e2e-test/scripts/profile.sh
  packages/server-wallet/jest/jest.e2e.config.js
  packages/server-wallet/jest/knex-setup-teardown.ts
  packages/server-wallet/package.json
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts
  packages/server-wallet/src/__test__/crash-tolerance/crash-tolerance.test.ts
  packages/server-wallet/src/__test__/create-and-close-channel/direct-funding.test.ts
  packages/server-wallet/src/__test__/create-and-close-channel/fake-funding.test.ts
  packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts
  packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts
  packages/server-wallet/src/chain-service/__chain-test__/stress.test.ts
  packages/server-wallet/src/config/defaults.ts
  packages/server-wallet/src/config/types.ts
  packages/server-wallet/src/config/utils.ts
  packages/server-wallet/src/db-admin/knexfile.ts
  packages/server-wallet/src/evm-validator.ts
  packages/server-wallet/src/index.ts
  packages/server-wallet/src/logger.ts
  packages/server-wallet/src/protocols/__test__/open-channel.test.ts
  packages/server-wallet/src/utilities/__test__/signatures.test.ts
  packages/server-wallet/src/wallet/__test__/add-my-state.test.ts
  packages/server-wallet/src/wallet/__test__/add-signed-state.test.ts
  packages/server-wallet/src/wallet/__test__/get-first-participant.test.ts
  packages/server-wallet/src/wallet/__test__/integration/close-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/create-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/create-ledger-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts
  packages/server-wallet/src/wallet/__test__/integration/sync-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/update-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/update-funding.test.ts
  packages/server-wallet/src/wallet/__test__/lock-app.test.ts
  packages/server-wallet/src/wallet/__test__/sign-state.test.ts
  packages/server-wallet/src/wallet/__test__/signing-address.test.ts
  packages/server-wallet/src/wallet/__test__/validate-transition.test.ts
  packages/server-wallet/src/wallet/store.ts
Labels: :carrot: conventional

#3013 test: fix defaultTestConfig use
  packages/server-wallet/src/handlers/__test__/single-app-updater.test.ts
Labels: :memo: conventional

#3016 build: deploy contracts to rinkeby
  packages/nitro-protocol/hardhat-deployments/rinkeby/ERC20AssetHolder.json
  packages/nitro-protocol/hardhat-deployments/rinkeby/ETHAssetHolder.json
  packages/nitro-protocol/hardhat-deployments/rinkeby/NitroAdjudicator.json
  packages/nitro-protocol/hardhat-deployments/rinkeby/Token.json
Labels: :memo: conventional

#2864 [breaking change (new config option)] consolidate chain service configuration options
  packages/server-wallet/deployment/deploy.ts
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts
  packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts
  packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts
  packages/server-wallet/src/chain-service/__chain-test__/stress.test.ts
  packages/server-wallet/src/chain-service/chain-service.ts
  packages/server-wallet/src/config/defaults.ts
  packages/server-wallet/src/config/types.ts
  packages/server-wallet/src/db-admin/knexfile.ts
  packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts
  packages/server-wallet/src/wallet/__test__/integration/update-funding.test.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: :carrot: conventional, :memo: conventional

#3018 build: update .env.rinkeby
  .env.rinkeby
  packages/nitro-protocol/readme.md
Labels: :memo: conventional

#3029 [nitro-protocol, docs-website] Resurrect docs#Contract API via patching hardhat
  netlify.toml
  packages/docs-website/docs/contract-api/contract-inheritance.mdx
  packages/docs-website/package.json
  packages/docs-website/sidebars.json
  packages/nitro-protocol/package.json
  packages/nitro-protocol/readme.md
  patches/hardhat+2.0.3.patch
  yarn.lock
Labels: :memo: conventional

#3023 [docs] Add section on outcome limits
  packages/docs-website/docs/protocol-tutorial/execute-state-transitions.md
  packages/docs-website/docs/protocol-tutorial/precautions-and-limits.md
  packages/docs-website/sidebars.json
  packages/nitro-protocol/readme.md
  packages/nitro-protocol/test/contracts/NitroAdjudicator/concludePushOutcomeAndTransferAll.test.ts
Labels: :memo: conventional

#3032 docs: minor tweaks to the docs website
  packages/docs-website/docs/docs/app-devs/hook-up-messaging.md
  packages/docs-website/docs/docs/app-devs/intro.md
  packages/docs-website/docs/docs/app-devs/make-api-calls.md
  packages/docs-website/docs/docs/app-devs/quick-start-contracts.md
  packages/docs-website/docs/docs/app-devs/quick-start-dapp.md
  packages/docs-website/docs/docs/app-devs/recommended-patterns.md
  packages/docs-website/docs/docs/implementation-notes/asset-holder.md
  packages/docs-website/docs/docs/implementation-notes/force-move.md
  packages/docs-website/docs/docs/implementation-notes/intro.md
  packages/docs-website/docs/docs/implementation-notes/nitro-adjudicator.md
  packages/docs-website/docs/docs/implementation-notes/null-app.md
  packages/docs-website/docs/docs/implementation-notes/single-asset-payments.md
  packages/docs-website/docs/docs/overview.md
  packages/docs-website/docs/docs/products.md
  packages/docs-website/docs/docs/protocol-docs/intro.md
  packages/docs-website/docs/docs/protocol-docs/quick-start.md
  packages/docs-website/docs/docs/protocol-docs/tutorial.md
  packages/docs-website/docs/docs/protocol-tutorial/clear-a-challenge.md
  packages/docs-website/docs/docs/protocol-tutorial/deposit-assets.md
  packages/docs-website/docs/docs/protocol-tutorial/execute-state-transitions.md
  packages/docs-website/docs/docs/protocol-tutorial/finalize-a-channel-happy.md
  packages/docs-website/docs/docs/protocol-tutorial/finalize-a-channel-sad.md
  packages/docs-website/docs/docs/protocol-tutorial/off-chain-funding.md
  packages/docs-website/docs/docs/protocol-tutorial/outcomes.md
  packages/docs-website/docs/docs/protocol-tutorial/precautions-and-limits.md
  packages/docs-website/docs/docs/protocol-tutorial/release-assets.md
  packages/docs-website/docs/docs/protocol-tutorial/understand-channel-storage.md
  packages/docs-website/docusaurus.config.js
  packages/docs-website/sidebars.json
Labels: :memo: conventional

#3019 [nitro-protocol] Run solhint (instead of prettier)
  packages/docs-website/docs/docs/implementation-notes/asset-holder.md
  packages/nitro-protocol/.solhint.json
  packages/nitro-protocol/contracts/AssetHolder.sol
  packages/nitro-protocol/contracts/ETHAssetHolder.sol
  packages/nitro-protocol/contracts/ForceMove.sol
  packages/nitro-protocol/contracts/test/TESTAssetHolder2.sol
  packages/nitro-protocol/contracts/test/TestErc20AssetHolder.sol
  packages/nitro-protocol/contracts/test/TestEthAssetHolder.sol
  packages/nitro-protocol/package.json
  packages/nitro-protocol/test/contracts/AssetHolder/setOutcome.test.ts
  packages/nitro-protocol/test/contracts/AssetHolder/transfer.test.ts
  yarn.lock
Labels: :memo: conventional

#3040 refactor: rename function
  packages/server-wallet/src/__test__/evm-validator.test.ts
  packages/server-wallet/src/evm-validator.ts
  packages/server-wallet/src/utilities/validate-transition.ts
Labels: :memo: conventional

#3051 docs: clarify role of functions
  packages/server-wallet/src/state-utils.ts
  packages/server-wallet/src/wallet/store.ts
Labels: :memo: conventional

#3049 feat: accept a list of indices in transfer method (rebased version of #3011)
  packages/nitro-protocol/contracts/AssetHolder.sol
  packages/nitro-protocol/contracts/interfaces/IAssetHolder.sol
  packages/nitro-protocol/contracts/test/TESTAssetHolder.sol
  packages/nitro-protocol/test/contracts/AssetHolder/transfer.test.ts
  packages/nitro-protocol/test/contracts/AssetHolder/transferAll.test.ts
Labels: :memo: conventional

#3064 chore: use tsconfig instead of tsConfig in config
  packages/nitro-protocol/config/jest/jest.config.js
  packages/server-wallet/jest/jest.config.js
Labels: :memo: conventional

#3062 Require Challenge Duration when creating a channel
  packages/client-api-schema/src/__tests__/sample_messages/requests/good.ts
  packages/client-api-schema/src/generated-schema.json
  packages/client-api-schema/src/methods/CreateChannel.ts
  packages/server-wallet/e2e-test/payer/client.ts
  packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts
  packages/server-wallet/src/__test__/crash-tolerance/crash-tolerance.test.ts
  packages/server-wallet/src/__test__/create-and-close-channel/direct-funding.test.ts
  packages/server-wallet/src/__test__/create-and-close-channel/fake-funding.test.ts
  packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts
  packages/server-wallet/src/__test__/test-helpers.ts
  packages/server-wallet/src/wallet/__test__/fixtures/create-channel.ts
  packages/server-wallet/src/wallet/__test__/integration/create-ledger-channel.test.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: :memo: conventional, challenging-v0, do not merge

#3074 Replace AssetTransferred with AllocationUpdated event
  packages/docs-website/docs/docs/app-devs/make-api-calls.md
  packages/docs-website/docs/docs/protocol-tutorial/release-assets.md
  packages/nitro-protocol/contracts/AssetHolder.sol
  packages/nitro-protocol/contracts/interfaces/IAssetHolder.sol
  packages/nitro-protocol/src/contract/asset-holder.ts
  packages/nitro-protocol/src/index.ts
  packages/nitro-protocol/test/contracts/AssetHolder/claim.test.ts
  packages/nitro-protocol/test/contracts/AssetHolder/claimAll.test.ts
  packages/nitro-protocol/test/contracts/AssetHolder/computeNewAllocation.test.ts
  packages/nitro-protocol/test/contracts/AssetHolder/transfer.test.ts
  packages/nitro-protocol/test/contracts/AssetHolder/transferAll.test.ts
  packages/nitro-protocol/test/contracts/NitroAdjudicator/concludePushOutcomeAndTransferAll.test.ts
  packages/nitro-protocol/test/contracts/NitroAdjudicator/pushOutcomeAndTransferAll.test.ts
  packages/nitro-protocol/test/test-helpers.ts
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts
  packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts
  packages/server-wallet/src/chain-service/chain-service.ts
  packages/server-wallet/src/chain-service/types.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: :memo: conventional

#3083 build: record estimated gas deployment cost of NitroAdjudicator
  packages/nitro-protocol/deployment/deploy.js
  packages/nitro-protocol/deployment/deploy.ts
Labels: :memo: conventional

#3087 refactor: swap JS based hashState to use wasm utility
  packages/server-wallet/src/models/channel.ts
Labels: :memo: conventional

#2761 📝💬🔏 Unsigned consensus protocol before signing ledger channel updates
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts
  packages/server-wallet/src/__test__/test-helpers.ts
  packages/server-wallet/src/db/migrations/20201014174041_ledgers.ts
  packages/server-wallet/src/db/migrations/20201201095501_ledger_proposals.ts
  packages/server-wallet/src/models/channel.ts
  packages/server-wallet/src/models/ledger-proposal.ts
  packages/server-wallet/src/protocols/__test__/process-ledger-queue.test.ts
  packages/server-wallet/src/protocols/actions.ts
  packages/server-wallet/src/protocols/process-ledger-queue.ts
  packages/server-wallet/src/protocols/state.ts
  packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts
  packages/server-wallet/src/wallet/__test__/integration/sync-channel.test.ts
  packages/server-wallet/src/wallet/store.ts
  packages/server-wallet/src/wallet/wallet-response.ts
  packages/server-wallet/src/wallet/wallet.ts
  packages/wallet-core/src/serde/wire-format/deserialize.ts
  packages/wallet-core/src/serde/wire-format/serialize.ts
  packages/wallet-core/src/types.ts
  packages/wallet-core/src/utils/outcome.ts
  packages/wire-format/src/generated-schema.json
  packages/wire-format/src/types.ts
Labels: server-wallet
