Repository statechannels/statechannels, pull requests merged in 2021-07, with the labels that each got.

#3642 swap `assetHolderAddress` column for `isLedgerChannel` column in channels table
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/db/migrations/20201014174041_ledgers.ts
  packages/server-wallet/src/db/migrations/20201027090001_channels_indexes.ts
  packages/server-wallet/src/engine/__test__/fixtures/test-channel.ts
  packages/server-wallet/src/engine/__test__/integration/create-ledger-channel.test.ts
  packages/server-wallet/src/engine/__test__/integration/join-channel.test.ts
  packages/server-wallet/src/engine/engine.ts
  packages/server-wallet/src/engine/store.ts
  packages/server-wallet/src/models/__test__/fixtures/channel.ts
  packages/server-wallet/src/models/channel.ts
Labels: 🧹 chore

#3647 Remove (another) duplicate abi.encode call
  packages/nitro-protocol/contracts/MultiAssetHolder.sol
  packages/nitro-protocol/gas-benchmarks/gas.ts
Labels: 🐎 performance, 🧹 chore

#3674 remove timeout configuration
  packages/nitro-protocol/test/contracts/ForceMove/_validSignatures.test.ts
Labels: testing, 🧹 chore

#3675 Update gas benchmarks to reflect London hardfork
  packages/nitro-protocol/gas-benchmarks/gas.ts
  packages/nitro-protocol/hardhat.config.ts
  packages/nitro-protocol/package.json
  patches/hardhat+2.5.0.patch
  yarn.lock
Labels: dependencies, 🐎 performance, 🧹 chore

#3678 Check guarantee and target outcome assets match
  packages/nitro-protocol/contracts/MultiAssetHolder.sol
  packages/nitro-protocol/gas-benchmarks/gas.ts
  packages/nitro-protocol/test/contracts/MultiAssetHolder/claim.test.ts
  packages/nitro-protocol/test/contracts/MultiAssetHolder/computeNewAllocationWithGuarantee.test.ts
Labels: testing

#3697 remove challengerAddress from ChannelData
  packages/docs-website/docs/docs/implementation-notes/force-move.md
  packages/docs-website/docs/docs/protocol-tutorial/release-assets.md
  packages/docs-website/docs/docs/protocol-tutorial/understand-adjudicator-status.md
  packages/nitro-protocol/contracts/ForceMove.sol
  packages/nitro-protocol/contracts/MultiAssetHolder.sol
  packages/nitro-protocol/contracts/NitroAdjudicator.sol
  packages/nitro-protocol/contracts/interfaces/IForceMove.sol
  packages/nitro-protocol/contracts/interfaces/IMultiAssetHolder.sol
  packages/nitro-protocol/contracts/test/TESTForceMove.sol
  packages/nitro-protocol/gas-benchmarks/benchmark.test.ts
  packages/nitro-protocol/gas-benchmarks/fixtures.ts
  packages/nitro-protocol/gas-benchmarks/gas.ts
  packages/nitro-protocol/notes/force-move-implementation.md
  packages/nitro-protocol/src/contract/challenge.ts
  packages/nitro-protocol/src/contract/channel-storage.ts
  packages/nitro-protocol/src/contract/transaction-creators/force-move.ts
  packages/nitro-protocol/src/contract/transaction-creators/nitro-adjudicator.ts
  packages/nitro-protocol/src/transactions.ts
  packages/nitro-protocol/test/contracts/ForceMove/challenge.test.ts
  packages/nitro-protocol/test/contracts/ForceMove/checkpoint.test.ts
  packages/nitro-protocol/test/contracts/ForceMove/respond.test.ts
  packages/nitro-protocol/test/contracts/ForceMove/storage.test.ts
  packages/nitro-protocol/test/contracts/MultiAssetHolder/claim.test.ts
  packages/nitro-protocol/test/contracts/MultiAssetHolder/transfer.test.ts
  packages/nitro-protocol/test/contracts/NitroAdjudicator/transferAllAssets.test.ts
  packages/nitro-protocol/test/test-helpers.ts
  packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts
  packages/server-wallet/src/chain-service/chain-service.ts
  packages/server-wallet/src/chain-service/mock-chain-service.ts
  packages/server-wallet/src/chain-service/types.ts
  packages/server-wallet/src/protocols/__test__/defund-channel.test.ts
  packages/server-wallet/src/protocols/__test__/defunder.test.ts
  packages/server-wallet/src/protocols/defunder.ts
Labels: 🐎 performance, 🧹 chore
