Repository statechannels/statechannels, pull requests merged in 2021-05, with the labels that each got.

#3534 Wallet now accepts a MessageServiceFactory
  packages/server-wallet/jest/with-peers-setup-teardown.ts
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/__test-with-peers__/crash-tolerance/crash-tolerance.test.ts
  packages/server-wallet/src/__test-with-peers__/create-and-close-channel/direct-funding.test.ts
  packages/server-wallet/src/__test-with-peers__/create-and-close-channel/fake-funding.test.ts
  packages/server-wallet/src/__test-with-peers__/create-and-close-channel/ledger-funding.test.ts
  packages/server-wallet/src/__test-with-peers__/sync-objectives.test.ts
  packages/server-wallet/src/__test-with-peers__/utils.ts
  packages/server-wallet/src/__test-with-peers__/wallet/approve-objective.test.ts
  packages/server-wallet/src/__test-with-peers__/wallet/close-channels.test.ts
  packages/server-wallet/src/__test-with-peers__/wallet/ensure-objectives.test.ts
  packages/server-wallet/src/__test-with-peers__/wallet/jumpstart.test.ts
  packages/server-wallet/src/engine/engine-response.ts
  packages/server-wallet/src/engine/engine.ts
  packages/server-wallet/src/engine/types.ts
  packages/server-wallet/src/message-service/legacy-test-message-service.ts
  packages/server-wallet/src/message-service/test-message-service.ts
  packages/server-wallet/src/message-service/types.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: :memo: conventional, ✨ enhancement

#3539 Add linux postgres instructions
  readme.md
Labels: :memo: conventional, 📖 documentation, 🧹 chore

#3547 Properly await knex.destroy in DB-Admin
  packages/server-wallet/src/db-admin/db-admin.ts
Labels: :memo: conventional

#3550 Readability suggestion
  packages/server-wallet/src/wallet/wallet.ts
Labels: :memo: conventional

#3541 Remove Objective Events from the engine
  packages/interop-tests/src/__test__/interop.test.ts
  packages/server-wallet/e2e-test/challenge.test.ts
  packages/server-wallet/e2e-test/e2e.test.ts
  packages/server-wallet/e2e-test/payer/client.ts
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/__test-with-peers__/utils.ts
  packages/server-wallet/src/__test-with-peers__/wallet/approve-objective.test.ts
  packages/server-wallet/src/__test-with-peers__/wallet/close-channels.test.ts
  packages/server-wallet/src/__test-with-peers__/wallet/ensure-objectives.test.ts
  packages/server-wallet/src/__test-with-peers__/wallet/jumpstart.test.ts
  packages/server-wallet/src/engine/__test__/challenge.test.ts
  packages/server-wallet/src/engine/__test__/integration/create-channel.test.ts
  packages/server-wallet/src/engine/__test__/integration/push-message.test.ts
  packages/server-wallet/src/engine/engine.ts
  packages/server-wallet/src/engine/multi-threaded-engine/worker.ts
  packages/server-wallet/src/engine/store.ts
  packages/server-wallet/src/engine/types.ts
  packages/server-wallet/src/message-service/test-message-service.ts
  packages/server-wallet/src/wallet/types.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: :memo: conventional, 🧹 chore
