Repository statechannels/statechannels, pull requests merged in 2021-04, with the labels that each got.

#3435 Swallow knex abort error in test tear down
  packages/server-wallet/jest/with-peers-setup-teardown.ts
Labels: :memo: conventional, 🧹 chore

#3426 Implement pure-function DirectFunder in wallet-core
  packages/wallet-core/src/protocols/direct-funder.ts
  packages/wallet-core/src/state-utils.ts
  packages/wallet-core/src/tests/direct-funder.test.ts
  packages/wallet-core/src/tests/test-helpers.ts
Labels: ✨ enhancement

#3436 Update wallet-core eslint
  packages/wallet-core/.eslintrc.js
Labels: 🧹 chore

#3437 Implement a minimally useful handling of pure direct funder logic
  packages/server-wallet/src/__test-with-peers__/sync-objectives.test.ts
  packages/server-wallet/src/engine/__test__/integration/push-message.test.ts
  packages/server-wallet/src/engine/engine.ts
  packages/server-wallet/src/models/signing-wallet.ts
  packages/server-wallet/src/state-utils.ts
  packages/server-wallet/src/version.ts
  packages/wallet-core/src/index.ts
  packages/wallet-core/src/protocols/direct-funder.ts
  packages/wallet-core/src/protocols/index.ts
  packages/wallet-core/src/serde/wire-format/serialize.ts
  packages/wallet-core/src/tests/direct-funder.test.ts
  packages/wallet-core/src/wire-protocol.ts
Labels: ✨ enhancement

#3438 Remove duplicate funding logic
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/__test-with-peers__/crash-tolerance/crash-tolerance.test.ts
  packages/server-wallet/src/__test-with-peers__/create-and-close-channel/direct-funding.test.ts
  packages/server-wallet/src/__test-with-peers__/create-and-close-channel/ledger-funding.test.ts
  packages/server-wallet/src/chain-service/types.ts
  packages/server-wallet/src/engine/__test__/integration/update-funding.test.ts
  packages/server-wallet/src/engine/engine.ts
  packages/server-wallet/src/engine/types.ts
Labels: 🧹 chore

#3440 Test synchronous LedgerManager logic
  packages/server-wallet/src/engine/__test__/fixtures/test-channel.ts
  packages/server-wallet/src/engine/__test__/fixtures/test-ledger-channel.ts
  packages/server-wallet/src/engine/store.ts
  packages/server-wallet/src/models/ledger-request.ts
  packages/server-wallet/src/protocols/__test__/ledger-manager.test.ts
  packages/server-wallet/src/protocols/challenge-submitter.ts
  packages/server-wallet/src/protocols/channel-closer.ts
  packages/server-wallet/src/protocols/channel-opener.ts
  packages/server-wallet/src/protocols/defund-channel.ts
  packages/server-wallet/src/protocols/ledger-manager.ts
Labels: 🧹 chore

#3446 Fix onOpenChannelObjective in xstate wallet
  packages/xstate-wallet/src/channel-wallet.ts
Labels: :memo: conventional

#3439 Pure DirectFunder protocol gets cranked to completion
  packages/server-wallet/src/__test-with-peers__/create-and-close-channel/direct-funding.test.ts
  packages/server-wallet/src/__test-with-peers__/sync-objectives.test.ts
  packages/server-wallet/src/engine/__test__/fixtures/utils.ts
  packages/server-wallet/src/engine/__test__/integration/join-channel.test.ts
  packages/server-wallet/src/engine/__test__/integration/push-message.test.ts
  packages/server-wallet/src/engine/engine.ts
  packages/wallet-core/config/jest/jest.config.js
  packages/wallet-core/src/index.ts
  packages/wallet-core/src/protocols/direct-funder.ts
  packages/wallet-core/src/tests/direct-funder.test.ts
  packages/wallet-core/src/tests/fixture.ts
  packages/wallet-core/src/tests/test-helpers.ts
Labels: ✨ enhancement

#3447 fix: remove updateFundingForChannels
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/engine/__test__/integration/update-funding.test.ts
  packages/server-wallet/src/engine/engine.ts
  packages/server-wallet/src/engine/types.ts
  readme.md
Labels: :memo: conventional

#3449 chore: remove obsolete benchmarks
  packages/server-wallet/benchmarks/get-channel.benchmark.ts
  packages/server-wallet/benchmarks/update-channel.benchmark.ts
  packages/server-wallet/benchmarks/wasm-signature.benchmark.ts
Labels: :memo: conventional

#3441 Separate LedgerProtocol from LedgerManager
  packages/server-wallet/src/engine/__test__/integration/sync-channel.test.ts
  packages/server-wallet/src/models/channel.ts
  packages/server-wallet/src/protocols/__test__/ledger-protocol.test.ts
  packages/server-wallet/src/protocols/ledger-manager.ts
  packages/server-wallet/src/protocols/ledger-protocol.ts
Labels: 🧹 chore

#3451 chore: add helper config for ninja-nitro tests
  packages/nitro-protocol/config/jest/jest.ninja-nitro.config.js
  packages/nitro-protocol/package.json
Labels: :memo: conventional, testing, 🧹 chore

#3427 Create Channels API
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts
  packages/server-wallet/src/__test-with-peers__/crash-tolerance/crash-tolerance.test.ts
  packages/server-wallet/src/__test-with-peers__/create-and-close-channel/direct-funding.test.ts
  packages/server-wallet/src/__test-with-peers__/create-and-close-channel/fake-funding.test.ts
  packages/server-wallet/src/__test-with-peers__/create-and-close-channel/ledger-funding.test.ts
  packages/server-wallet/src/__test-with-peers__/ensure-objectives.test.ts
  packages/server-wallet/src/__test-with-peers__/sync-objectives.test.ts
  packages/server-wallet/src/engine/engine.ts
  packages/server-wallet/src/engine/types.ts
  packages/server-wallet/src/models/objective.ts
  packages/server-wallet/src/wallet/index.ts
  packages/server-wallet/src/wallet/types.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: :memo: conventional, ✨ enhancement

#3465 Add EOA Balances check to deployAndPayout test
  packages/nitro-protocol/test/contracts/ninja-nitro/AdjudicatorFactory/deployAndPayout.test.ts
  packages/nitro-protocol/test/contracts/ninja-nitro/SingleChannelAdjudicator/transfer.test.ts
Labels: testing

#3473 chore: remove duplicate calls in xstate-wallet application workflow
  packages/xstate-wallet/src/workflows/application.ts
Labels: :memo: conventional

#3457 Add Jumpstart objectives method
  packages/server-wallet/jest/custom-matchers.ts
  packages/server-wallet/jest/with-peers-setup-teardown.ts
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/__test-with-peers__/crash-tolerance/crash-tolerance.test.ts
  packages/server-wallet/src/__test-with-peers__/utils.ts
  packages/server-wallet/src/__test-with-peers__/wallet/ensure-objectives.test.ts
  packages/server-wallet/src/__test-with-peers__/wallet/jumpstart.test.ts
  packages/server-wallet/src/__test__/globals.d.ts
  packages/server-wallet/src/engine/engine.ts
  packages/server-wallet/src/engine/store.ts
  packages/server-wallet/src/wallet/types.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: :memo: conventional, ✨ enhancement

#3484 Include jest typescript folders in linting
  packages/server-wallet/.eslintignore
  packages/server-wallet/jest/custom-matchers.ts
  packages/server-wallet/jest/jest.config.js
  packages/server-wallet/jest/knex-setup-teardown.ts
  packages/server-wallet/jest/test-teardown.ts
  packages/server-wallet/jest/with-peers-setup-teardown.ts
Labels: :memo: conventional, 🧹 chore

#3493 Refactor with peers to no longer rely on global variables
  packages/server-wallet/jest/with-peers-setup-teardown.ts
  packages/server-wallet/src/__test-with-peers__/crash-tolerance/crash-tolerance.test.ts
  packages/server-wallet/src/__test-with-peers__/create-and-close-channel/direct-funding.test.ts
  packages/server-wallet/src/__test-with-peers__/create-and-close-channel/fake-funding.test.ts
  packages/server-wallet/src/__test-with-peers__/create-and-close-channel/ledger-funding.test.ts
  packages/server-wallet/src/__test-with-peers__/sync-objectives.test.ts
  packages/server-wallet/src/__test-with-peers__/utils.ts
  packages/server-wallet/src/__test-with-peers__/wallet/ensure-objectives.test.ts
  packages/server-wallet/src/__test-with-peers__/wallet/jumpstart.test.ts
  packages/server-wallet/src/message-service/test-message-service.ts
Labels: :memo: conventional, 🧹 chore

#3459 [ninja-nitro] Implement claim
  packages/nitro-protocol/contracts/ForceMove.sol
  packages/nitro-protocol/contracts/interfaces/IForceMove.sol
  packages/nitro-protocol/contracts/ninja-nitro/OutcomeTransformations.sol
  packages/nitro-protocol/contracts/ninja-nitro/SingleChannelAdjudicator.sol
  packages/nitro-protocol/src/ninja-nitro/helpers.ts
  packages/nitro-protocol/test/contracts/ninja-nitro/SingleChannelAdjudicator/claim.test.ts
  packages/nitro-protocol/test/contracts/ninja-nitro/SingleChannelAdjudicator/computeNewAllocationWithGuarantee.test.ts
  packages/nitro-protocol/test/test-helpers.ts
Labels: 🔒 security

#3512 Fix EnsureObjective
  packages/server-wallet/jest/custom-matchers.ts
  packages/server-wallet/jest/with-peers-setup-teardown.ts
  packages/server-wallet/src/__test-with-peers__/wallet/ensure-objectives.test.ts
  packages/server-wallet/src/__test-with-peers__/wallet/jumpstart.test.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: :memo: conventional, 🐛 bug

#3516 chore: add no self compare lint rule
  .eslintrc.js
Labels: :memo: conventional

#3509 [browser-wallet] refactor: collapse approve objective into crank objective function
  packages/browser-wallet/src/channel-wallet.ts
Labels: :memo: conventional

#3500 Engine-Response returns messages by objective id
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/engine/__test__/sync-objectives.test.ts
  packages/server-wallet/src/engine/engine-response.ts
  packages/server-wallet/src/engine/engine.ts
  packages/server-wallet/src/engine/types.ts
  packages/server-wallet/src/index.ts
  packages/server-wallet/src/protocols/channel-closer.ts
  packages/server-wallet/src/protocols/channel-opener.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: :memo: conventional, ✨ enhancement

#3520 [browser-wallet] Guarantee type safety for rich objective feeds
  packages/browser-wallet/src/channel-wallet.ts
  packages/browser-wallet/src/store/store.ts
Labels: :memo: conventional

#3521 build: remove unused @material-ui/icons dependency
  packages/browser-wallet/package.json
  yarn.lock
Labels: :memo: conventional

#3524 Fix pushMessage updating approved objective statuses to pending
  packages/server-wallet/src/engine/__test__/fixtures/test-channel.ts
  packages/server-wallet/src/engine/__test__/integration/join-channel.test.ts
  packages/server-wallet/src/engine/__test__/integration/push-message.test.ts
  packages/server-wallet/src/engine/__test__/sync-objectives.test.ts
  packages/server-wallet/src/engine/engine.ts
  packages/server-wallet/src/engine/store.ts
  packages/server-wallet/src/models/__test__/objectives.test.ts
  packages/server-wallet/src/models/objective.ts
  packages/server-wallet/src/objectives/close-channel.ts
  packages/server-wallet/src/protocols/__test__/challenge-submitter.test.ts
  packages/server-wallet/src/protocols/__test__/close-channel.test.ts
  packages/server-wallet/src/protocols/__test__/defund-channel.test.ts
  packages/server-wallet/src/protocols/__test__/defunder.test.ts
Labels: :memo: conventional, 🐛 bug

#3526 add test for create2ing the channel
  packages/nitro-protocol/contracts/ninja-nitro/AdjudicatorFactory.sol
  packages/nitro-protocol/test/contracts/ninja-nitro/AdjudicatorFactory/createChannel.test.ts
Labels: 🧹 chore

#3529 chore: update PR template with notion links
  .github/pull_request_template.md
Labels: :memo: conventional, 🧹 chore

#3527 Update ApproveObjectives to return correct status on objectives
  packages/server-wallet/src/__test-with-peers__/utils.ts
  packages/server-wallet/src/__test-with-peers__/wallet/approve-objective.test.ts
  packages/server-wallet/src/__test-with-peers__/wallet/ensure-objectives.test.ts
  packages/server-wallet/src/engine/engine.ts
  packages/server-wallet/src/engine/store.ts
  packages/server-wallet/src/message-service/test-message-service.ts
Labels: :memo: conventional, 🐛 bug

#3485 Add approveObjectives API
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/__test-with-peers__/utils.ts
  packages/server-wallet/src/__test-with-peers__/wallet/approve-objective.test.ts
  packages/server-wallet/src/__test-with-peers__/wallet/ensure-objectives.test.ts
  packages/server-wallet/src/engine/engine.ts
  packages/server-wallet/src/engine/store.ts
  packages/server-wallet/src/message-service/test-message-service.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: :memo: conventional, ✨ enhancement
