Repository statechannels/statechannels, pull requests merged in 2021-01, with the labels that each got.

#3098 docs: fix many broken links
  packages/client-api-schema/client-api-schema.api.md
  packages/docs-website/docs/docs/app-devs/make-api-calls.md
  packages/docs-website/docs/docs/app-devs/quick-start-contracts.md
  packages/docs-website/docs/docs/app-devs/quick-start-dapp.md
  packages/docs-website/docs/docs/app-devs/recommended-patterns.md
  packages/docs-website/docs/docs/implementation-notes/asset-holder.md
  packages/docs-website/docs/docs/implementation-notes/force-move.md
  packages/docs-website/docs/docs/implementation-notes/nitro-adjudicator.md
  packages/docs-website/docs/docs/implementation-notes/single-asset-payments.md
  packages/docs-website/docs/docs/overview.md
  packages/docs-website/docs/docs/protocol-docs/tutorial.md
  packages/docs-website/docs/docs/protocol-tutorial/clear-a-challenge.md
  packages/docs-website/docs/docs/protocol-tutorial/execute-state-transitions.md
  packages/docs-website/docs/docs/protocol-tutorial/finalize-a-channel-happy.md
  packages/docs-website/docs/docs/protocol-tutorial/finalize-a-channel-sad.md
  packages/docs-website/docs/docs/protocol-tutorial/off-chain-funding.md
  packages/docs-website/docs/docs/protocol-tutorial/precautions-and-limits.md
  packages/docs-website/docs/docs/protocol-tutorial/understand-channel-storage.md
Labels: :memo: conventional

#3101 docs: replace forceMove with challenge
  packages/docs-website/docs/docs/protocol-tutorial/finalize-a-channel-sad.md
Labels: :memo: conventional

#3102 build: throw error on broken links
  packages/docs-website/docusaurus.config.js
Labels: :memo: conventional

#3103 build: fix typos
  .circleci/config.yml
Labels: :memo: conventional

#3095 refactor: change Wallet from object to abstract class
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/objectives/types.ts
  packages/server-wallet/src/wallet/__test__/integration/update-funding.test.ts
  packages/server-wallet/src/wallet/index.ts
Labels: :memo: conventional

#3106 build: do not use --scope with lerna when deciding whether to build the docs
  .circleci/config.yml
  packages/docs-website/package.json
Labels: :memo: conventional

#3104 refactor: make fundingStatus optional in the ChannelResult
  packages/client-api-schema/src/data-types.ts
  packages/client-api-schema/src/generated-schema.json
  packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts
  packages/server-wallet/src/__test__/test-helpers.ts
  packages/server-wallet/src/models/__test__/channel.test.ts
  packages/server-wallet/src/models/channel.ts
  packages/server-wallet/src/protocols/open-channel.ts
  packages/server-wallet/src/protocols/state.ts
Labels: :memo: conventional

#3089 refactor open channel
  packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts
  packages/server-wallet/src/__test__/crash-tolerance/crash-tolerance.test.ts
  packages/server-wallet/src/__test__/create-and-close-channel/direct-funding.test.ts
  packages/server-wallet/src/__test__/create-and-close-channel/fake-funding.test.ts
  packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts
  packages/server-wallet/src/models/channel.ts
  packages/server-wallet/src/protocols/__test__/open-channel.test.ts
  packages/server-wallet/src/protocols/direct-funder.ts
  packages/server-wallet/src/protocols/ledger-funder.ts
  packages/server-wallet/src/protocols/open-channel.ts
  packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts
  packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts
  packages/server-wallet/src/wallet/__test__/integration/update-funding.test.ts
  packages/server-wallet/src/wallet/store.ts
Labels: :memo: conventional

#3111 Add challenge status to channel
  packages/client-api-schema/src/__tests__/sample_messages/notifications/good.ts
  packages/client-api-schema/src/__tests__/sample_messages/responses/good.ts
  packages/client-api-schema/src/data-types.ts
  packages/client-api-schema/src/generated-schema.json
  packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts
  packages/server-wallet/src/chain-service/chain-service.ts
  packages/server-wallet/src/chain-service/types.ts
  packages/server-wallet/src/db/migrations/20201211180815_challenge_status.ts
  packages/server-wallet/src/models/__test__/challenge-status.test.ts
  packages/server-wallet/src/models/challenge-status.ts
  packages/server-wallet/src/models/channel.ts
  packages/server-wallet/src/protocols/__test__/fixtures/channel-state.ts
  packages/server-wallet/src/protocols/state.ts
  packages/server-wallet/src/wallet/store.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: challenging-v0

#3108 perf: remove claimAll from AssetHolder interface
  packages/nitro-protocol/contracts/AssetHolder.sol
  packages/nitro-protocol/contracts/interfaces/IAssetHolder.sol
  packages/nitro-protocol/test/contracts/AssetHolder/claimAll.test.ts
Labels: :memo: conventional

#3117 refactor: rename file
  packages/server-wallet/src/objectives/objective-manager.ts
  packages/server-wallet/src/protocols/__test__/open-channel.test.ts
  packages/server-wallet/src/protocols/channel-opener.ts
Labels: :memo: conventional

#3121 Introduce Submit Challenge Protocol
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/models/challenge-status.ts
  packages/server-wallet/src/models/objective.ts
  packages/server-wallet/src/objectives/objective-manager.ts
  packages/server-wallet/src/protocols/__test__/challenge-submitter.test.ts
  packages/server-wallet/src/protocols/challenge-submitter.ts
  packages/server-wallet/src/wallet/__test__/challenge.test.ts
  packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts
  packages/server-wallet/src/wallet/__test__/fixtures/test-ledger-channel.ts
  packages/server-wallet/src/wallet/store.ts
  packages/server-wallet/src/wallet/types.ts
  packages/server-wallet/src/wallet/wallet-response.ts
  packages/server-wallet/src/wallet/wallet.ts
  packages/wallet-core/src/serde/wire-format/deserialize.ts
  packages/wallet-core/src/types.ts
Labels: :memo: conventional

#3125 Fix incorrect method name
  packages/server-wallet/src/protocols/challenge-submitter.ts
Labels: :memo: conventional

#3130 refactor: decouple logger from evm transition validation
  packages/server-wallet/src/__test__/evm-validator.test.ts
  packages/server-wallet/src/evm-validator.ts
  packages/server-wallet/src/utilities/validate-transition.ts
Labels: :memo: conventional

#3127 feat: store challenge state
  packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts
  packages/server-wallet/src/chain-service/chain-service.ts
  packages/server-wallet/src/chain-service/types.ts
  packages/server-wallet/src/db/migrations/20210111135843_add_challenge_state.ts
  packages/server-wallet/src/models/__test__/challenge-status.test.ts
  packages/server-wallet/src/models/challenge-status.ts
  packages/server-wallet/src/protocols/__test__/challenge-submitter.test.ts
  packages/server-wallet/src/wallet/__test__/challenge.test.ts
  packages/server-wallet/src/wallet/store.ts
  packages/server-wallet/src/wallet/wallet.ts
  packages/wallet-core/src/state-utils.ts
Labels: challenging-v0

#3141 fix: correct nitro-protocol dependencies
  packages/nitro-protocol/package.json
Labels: :memo: conventional

#3145 test: prefer nullish coallescing operator ?? to ||
  packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts
Labels: :memo: conventional

#3144 refactor: use instanceof test for UniqueViolationError
  packages/server-wallet/src/wallet/store.ts
Labels: :memo: conventional

#3133 Defund Channel Protocol
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/db/migrations/20210112164123_add_push_outcome_status.ts
  packages/server-wallet/src/models/chain-service-request.ts
  packages/server-wallet/src/models/objective.ts
  packages/server-wallet/src/objectives/objective-manager.ts
  packages/server-wallet/src/protocols/__test__/defund-channel.test.ts
  packages/server-wallet/src/protocols/challenge-submitter.ts
  packages/server-wallet/src/protocols/channel-opener.ts
  packages/server-wallet/src/protocols/close-channel.ts
  packages/server-wallet/src/protocols/defund-channel.ts
  packages/server-wallet/src/wallet/__test__/challenge.test.ts
  packages/server-wallet/src/wallet/store.ts
  packages/server-wallet/src/wallet/wallet.ts
  packages/wallet-core/src/types.ts
Labels: challenging-v0

#3152 test: default to a random channel nonce if none is provided.
  packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts
Labels: :memo: conventional

#3155 perf: TestChannel nonce is incrementing, not random
  packages/server-wallet/src/handlers/__test__/single-app-updater.test.ts
  packages/server-wallet/src/protocols/__test__/ledger-manager.test.ts
  packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts
Labels: :memo: conventional

#3153 test: enhance TestLedgerChannel
  packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts
  packages/server-wallet/src/wallet/__test__/fixtures/test-ledger-channel.ts
Labels: :memo: conventional

#3156 ci: introduce a branch that runs all tests
  .circleci/config.yml
Labels: :memo: conventional

#3163 test: rewrite ledger-manager.test.ts (part 1)
  packages/server-wallet/src/handlers/__test__/single-app-updater.test.ts
  packages/server-wallet/src/protocols/__test__/ledger-manager.test.ts
  packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts
  packages/server-wallet/src/wallet/__test__/fixtures/test-ledger-channel.ts
Labels: :memo: conventional

#3166 refactor: introduce NULL_APP_DATA const
  packages/server-wallet/src/protocols/ledger-manager.ts
  packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts
  packages/server-wallet/src/wallet/__test__/integration/create-ledger-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts
  packages/server-wallet/src/wallet/wallet.ts
  packages/wallet-core/src/constants.ts
  packages/wallet-core/src/index.ts
Labels: :memo: conventional

#3154 fix: support fake funding in directFundingStatus
  packages/server-wallet/src/protocols/state.ts
Labels: :memo: conventional

#3167 test: add missing tables to truncateDB()
  packages/server-wallet/src/db-admin/db-admin.ts
Labels: :memo: conventional

#3172 Fix Master
  packages/server-wallet/src/db-admin/db-admin.ts
Labels: :memo: conventional

#3161 feat: handle Concluded event from adjudicator
  packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts
  packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts
  packages/server-wallet/src/chain-service/chain-service.ts
  packages/server-wallet/src/protocols/__test__/defund-channel.test.ts
  packages/server-wallet/src/protocols/defund-channel.ts
Labels: :memo: conventional

#3173 Fix Master AGAIN
  packages/server-wallet/src/wallet/store.ts
Labels: :memo: conventional

#3164 build: trigger canary release on a schedule
  .github/workflows/publish-canary.yml
Labels: :memo: conventional

#3184 docs: remove comment
  packages/docs-website/docs/docs/overview.md
Labels: :book: documentation, :memo: conventional

#3183 Wallet.Create is now async
  packages/server-wallet/e2e-test/e2e.test.ts
  packages/server-wallet/e2e-test/payer/app.ts
  packages/server-wallet/e2e-test/payer/client.ts
  packages/server-wallet/e2e-test/payer/start.ts
  packages/server-wallet/e2e-test/receiver/app.ts
  packages/server-wallet/e2e-test/receiver/controller.ts
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts
  packages/server-wallet/src/__test__/crash-tolerance/crash-tolerance.test.ts
  packages/server-wallet/src/__test__/create-and-close-channel/direct-funding.test.ts
  packages/server-wallet/src/__test__/create-and-close-channel/fake-funding.test.ts
  packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts
  packages/server-wallet/src/wallet/__test__/challenge.test.ts
  packages/server-wallet/src/wallet/__test__/integration/close-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/create-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/create-ledger-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts
  packages/server-wallet/src/wallet/__test__/integration/sync-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/update-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/update-funding.test.ts
  packages/server-wallet/src/wallet/index.ts
  packages/server-wallet/src/wallet/multi-threaded-wallet/index.ts
  packages/server-wallet/src/wallet/multi-threaded-wallet/worker.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: :bomb: BREAKING CHANGE, :memo: conventional, bug

#3185 refactor: add comment on handling cranking errors
  packages/server-wallet/src/protocols/ledger-manager.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: :memo: conventional

#3187 Fix race condition in Funding table writes
  packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts
  packages/server-wallet/src/models/funding.ts
  packages/server-wallet/src/wallet/store.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: :memo: conventional, bug

#3192 test: undelete old test suite
  packages/server-wallet/src/protocols/__test__/ledger-manager-protocol.test.ts
Labels: :memo: conventional

#3193 refactor: rip out getFirstParticipant() from store
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/wallet/__test__/get-first-participant.test.ts
  packages/server-wallet/src/wallet/store.ts
  packages/server-wallet/src/wallet/types.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: :memo: conventional

#3200 chore: remove console.log
  packages/server-wallet/src/protocols/__test__/ledger-manager.test.ts
Labels: :memo: conventional

#3194 chore: mergeMessages -> mergeOutputs
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/wallet/types.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: :memo: conventional

#3211 Improve PR template
  .github/pull_request_template.md
Labels: :broom: chore

#3210 chore: remove no-op method from SingleThreadedWallet
  packages/server-wallet/e2e-test/payer/client.ts
  packages/server-wallet/e2e-test/receiver/controller.ts
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/wallet/wallet.ts
Labels: :bomb: BREAKING CHANGE, :memo: conventional

#3199 chore: improve e2e logging
  packages/server-wallet/e2e-test/e2e-utils.ts
  packages/server-wallet/e2e-test/logger.ts
  packages/server-wallet/e2e-test/payer/client.ts
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/config/types.ts
  packages/server-wallet/src/logger.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: :memo: conventional

#3219 Store and challenge with initial supported state for ledger channels
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/db/migrations/20210126122744_add_initial_support_to_channel.ts
  packages/server-wallet/src/models/channel.ts
  packages/server-wallet/src/models/objective.ts
  packages/server-wallet/src/protocols/__test__/challenge-submitter.test.ts
  packages/server-wallet/src/protocols/__test__/ledger-manager.test.ts
  packages/server-wallet/src/protocols/challenge-submitter.ts
  packages/server-wallet/src/protocols/ledger-manager.ts
  packages/server-wallet/src/wallet/__test__/challenge.test.ts
  packages/server-wallet/src/wallet/store.ts
  packages/server-wallet/src/wallet/types.ts
  packages/server-wallet/src/wallet/wallet.ts
  packages/wallet-core/src/types.ts
Labels: :memo: conventional, enhancement

#3221 ci: succeed early if canary already published
  .github/workflows/publish-canary.yml
Labels: :memo: conventional

#3129 Refactor the process ledger queue protocol
  packages/server-wallet/src/db-admin/db-admin.ts
  packages/server-wallet/src/protocols/__test__/ledger-manager-protocol.test.ts
  packages/server-wallet/src/protocols/__test__/ledger-manager.test.ts
  packages/server-wallet/src/protocols/ledger-manager.ts
  packages/server-wallet/src/wallet/__test__/integration/create-ledger-channel.test.ts
Labels: :memo: conventional
