Repository statechannels/statechannels, pull requests merged in 2021-03, with the labels that each got.

#3339 chore: remove unused jest.stress.config file
  packages/server-wallet/jest/jest.stress.config.js
Labels: :memo: conventional, testing, 🧹 chore

#3338 circleCI: Separate with-peers tests from other server-wallet tests
  .circleci/config.yml
  packages/server-wallet/jest/jest.with-peers.config.js
  packages/server-wallet/src/__test-with-peers__/crash-tolerance/crash-tolerance.seqdiag
  packages/server-wallet/src/__test-with-peers__/crash-tolerance/crash-tolerance.test.ts
  packages/server-wallet/src/__test-with-peers__/create-and-close-channel/close-channel-simplified.seqdiag
  packages/server-wallet/src/__test-with-peers__/create-and-close-channel/direct-funding-simplified.seqdiag
  packages/server-wallet/src/__test-with-peers__/create-and-close-channel/direct-funding.test.ts
  packages/server-wallet/src/__test-with-peers__/create-and-close-channel/fake-funding-simplified.seqdiag
  packages/server-wallet/src/__test-with-peers__/create-and-close-channel/fake-funding.test.ts
  packages/server-wallet/src/__test-with-peers__/create-and-close-channel/ledger-funding.test.ts
  packages/server-wallet/src/__test-with-peers__/sync-objectives.test.ts
Labels: :memo: conventional, testing, 🧹 chore

#3360 chore: update PR template with additional project management checkbox
  .github/pull_request_template.md
Labels: :memo: conventional, 🧹 chore

#3359 test: insert a case for defunding a single erc20
  packages/nitro-protocol/test/contracts/NitroAdjudicator/concludePushOutcomeAndTransferAll.test.ts
Labels: 🧹 chore

#3370 chore: use === instead of == for comparison
  packages/server-wallet/e2e-test/scripts/generate-profile-data.ts
  packages/server-wallet/src/utilities/validate-transition.ts
  packages/server-wallet/src/wallet/store.ts
Labels: :memo: conventional

#3378 Cleanup test contract deployment
  packages/nitro-protocol/.env
  packages/nitro-protocol/contracts/test/TESTAssetHolder2.sol
  packages/nitro-protocol/contracts/test/TestEthAssetHolder.sol
  packages/nitro-protocol/contracts/test/TestEthAssetHolder2.sol
  packages/nitro-protocol/deployment/deploy-test-contracts.ts
  packages/nitro-protocol/jest/contract-test-setup.ts
  packages/nitro-protocol/readme.md
  packages/nitro-protocol/test/contracts/AssetHolder/setOutcome.test.ts
  packages/nitro-protocol/test/contracts/ETHAssetHolder/deposit.test.ts
  packages/nitro-protocol/test/contracts/NitroAdjudicator/concludePushOutcomeAndTransferAll.test.ts
  packages/nitro-protocol/test/contracts/NitroAdjudicator/pushOutcome.test.ts
  packages/nitro-protocol/test/contracts/NitroAdjudicator/pushOutcomeAndTransferAll.test.ts
Labels: 🧹 chore

#3369 Implement a basic Messaging Service
  packages/server-wallet/jest/with-peers-setup-teardown.ts
  packages/server-wallet/src/__test-with-peers__/crash-tolerance/crash-tolerance.test.ts
  packages/server-wallet/src/__test-with-peers__/create-and-close-channel/direct-funding.test.ts
  packages/server-wallet/src/__test-with-peers__/create-and-close-channel/fake-funding.test.ts
  packages/server-wallet/src/__test-with-peers__/create-and-close-channel/ledger-funding.test.ts
  packages/server-wallet/src/__test-with-peers__/utils.ts
  packages/server-wallet/src/__test__/test-helpers.ts
  packages/server-wallet/src/message-service/test-message-service.ts
  packages/server-wallet/src/message-service/types.ts
Labels: :memo: conventional, ✨ enhancement

#3391 chore: Remove DOM Lib from server-wallet tsconfig
  packages/server-wallet/package.json
  packages/server-wallet/src/evm-validator.ts
  packages/server-wallet/tsconfig.json
  yarn.lock
Labels: :memo: conventional, 🧹 chore

#3393 change many forceMove -> challenge
  packages/docs-website/docs/docs/implementation-notes/force-move.md
  packages/docs-website/docs/docs/implementation-notes/null-app.md
  packages/docs-website/docs/docs/protocol-tutorial/finalize-a-channel-sad.md
  packages/docs-website/docs/docs/protocol-tutorial/understand-adjudicator-status.md
  packages/nitro-protocol/notes/blog-posts/gas-optimizations/gas-usage-chart.py
  packages/nitro-protocol/notes/force-move-implementation.md
  packages/nitro-protocol/src/transactions.ts
  packages/nitro-protocol/test/contracts/ForceMove/challenge.test.ts
Labels: 📖 documentation, 🧹 chore

#3376 EnsureObjective
  packages/server-wallet/jest/with-peers-setup-teardown.ts
  packages/server-wallet/src/__test-with-peers__/crash-tolerance/crash-tolerance.test.ts
  packages/server-wallet/src/__test-with-peers__/create-and-close-channel/direct-funding.test.ts
  packages/server-wallet/src/__test-with-peers__/create-and-close-channel/fake-funding.test.ts
  packages/server-wallet/src/__test-with-peers__/ensure-objectives.test.ts
  packages/server-wallet/src/__test-with-peers__/utils.ts
  packages/server-wallet/src/channel-manager.ts
  packages/server-wallet/src/message-service/test-message-service.ts
  packages/server-wallet/src/message-service/utils.ts
Labels: :memo: conventional, ✨ enhancement, 🥕 conventional

#3399 build: cache xstate-wallet node_modules on circle ci
  .circleci/config.yml
Labels: :memo: conventional

#3417 Don't run knex-setup-teardown for with-peers test
  packages/server-wallet/jest/jest.with-peers.config.js
Labels: 🐛 bug

#3421 chore: fix interop test import
  packages/interop-tests/src/__test__/interop.test.ts
Labels: :memo: conventional

#3419 Save With-Peers test logs
  packages/server-wallet/jest/with-peers-setup-teardown.ts
Labels: ✨ enhancement

#3422 Fix resource contention between server-wallet and interop-tests packages
  .circleci/config.yml
  packages/interop-tests/jest/chain-setup.ts
  packages/interop-tests/src/__test__/interop.test.ts
  packages/server-wallet/deployment/deploy.ts
Labels: :memo: conventional

#3424 test: log out gas cost for increaseAllowance
  packages/nitro-protocol/test/contracts/ERC20AssetHolder/deposit.test.ts
Labels: :memo: conventional
