Repository statechannels/statechannels, pull requests merged in 2021-06, with the labels that each got.

#3546 Remove all events from engine
  packages/interop-tests/src/__test__/interop.test.ts
  packages/server-wallet/e2e-test/e2e.test.ts
  packages/server-wallet/e2e-test/payer/client.ts
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts
  packages/server-wallet/src/engine/engine-response.ts
  packages/server-wallet/src/engine/engine.ts
  packages/server-wallet/src/engine/multi-threaded-engine/index.ts
  packages/server-wallet/src/engine/multi-threaded-engine/manager.ts
  packages/server-wallet/src/engine/multi-threaded-engine/worker.ts
  packages/server-wallet/src/engine/types.ts
  packages/server-wallet/src/objectives/types.ts
Labels: :memo: conventional, 🧹 chore

#3573 Add a toConsumeGas jest matcher
  packages/nitro-protocol/gas-benchmarks/benchmark.test.ts
  packages/nitro-protocol/gas-benchmarks/vanillaSetup.ts
Labels: 🧹 chore

#3577 Add a diff indicator (+/- X) to error message of toConsumeGas
  packages/nitro-protocol/gas-benchmarks/vanillaSetup.ts
Labels: :memo: conventional, testing

#3586 fix some eslint settings and warnings
  packages/nitro-protocol/gas-benchmarks/vanillaSetup.ts
  packages/nitro-protocol/package.json
Labels: 🧹 chore

#3581 docs: move ledger update algorithm docs
  packages/server-wallet/src/protocols/ledger-manager.ts
  packages/server-wallet/src/protocols/ledger-protocol.ts
Labels: :memo: conventional

#3590 Remove deployment code from devtools and remove etherlime dependency
  packages/browser-wallet/deployment/deploy.ts
  packages/devtools/.eslintignore
  packages/devtools/package.json
  packages/devtools/src/constants.ts
  packages/devtools/src/ganache/deployer-with-cache.ts
  packages/devtools/src/ganache/deployer.ts
  packages/devtools/src/ganache/index.ts
  packages/devtools/src/ganache/server.ts
  packages/devtools/src/index.ts
  packages/devtools/src/types.ts
  packages/interop-tests/jest/chain-setup.ts
  packages/interop-tests/src/__test__/interop.test.ts
  packages/nitro-protocol/deployment/deploy-test-contracts.ts
  packages/nitro-protocol/package.json
  packages/server-wallet/deployment/deploy.ts
  packages/server-wallet/jest/chain-setup.ts
  packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts
  packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts
  packages/server-wallet/src/chain-service/__chain-test__/stress.test.ts
  packages/wallet-core/deployment/deploy.js
  yarn.lock
Labels: 🧹 chore

#3620 move transferAll test cases to transfer file
  packages/nitro-protocol/test/contracts/AssetHolder/claim.test.ts
  packages/nitro-protocol/test/contracts/AssetHolder/claimAll.test.ts
  packages/nitro-protocol/test/contracts/AssetHolder/transfer.test.ts
  packages/nitro-protocol/test/contracts/AssetHolder/transferAll.test.ts
Labels: 🧹 chore
