Repository statechannels/statechannels, pull requests merged in 2021-02, with the labels that each got.

#3243 Wallet emits 'objectiveStarted' & 'objectiveSucceeded' events
  packages/server-wallet/e2e-test/challenge.test.ts
  packages/server-wallet/e2e-test/e2e.test.ts
  packages/server-wallet/e2e-test/payer/client.ts
  packages/server-wallet/jest/jest.e2e.config.js
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/models/objective.ts
  packages/server-wallet/src/protocols/challenge-submitter.ts
  packages/server-wallet/src/protocols/channel-closer.ts
  packages/server-wallet/src/protocols/channel-opener.ts
  packages/server-wallet/src/protocols/defund-channel.ts
  packages/server-wallet/src/wallet/__test__/challenge.test.ts
  packages/server-wallet/src/wallet/__test__/integration/create-channel.test.ts
  packages/server-wallet/src/wallet/store.ts
  packages/server-wallet/src/wallet/types.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: enhancement

#3247 docs: add note about checking in reports
  readme.md
Labels: :book: documentation, :memo: conventional

#3250 refactor: make toWireObjective type safe / more robust
  packages/server-wallet/src/models/objective.ts
Labels: :broom: chore, :memo: conventional

#3251 fix: make participants a required property of objectives
  packages/server-wallet/src/models/objective.ts
  packages/server-wallet/src/protocols/__test__/challenge-submitter.test.ts
  packages/server-wallet/src/protocols/__test__/defund-channel.test.ts
  packages/wallet-core/src/serde/wire-format/deserialize.ts
  packages/wallet-core/src/types.ts
  packages/wire-format/src/generated-schema.json
  packages/wire-format/src/types.ts
Labels: :broom: chore, :memo: conventional

#3246 New objectives are returned in ChannelResults
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts
  packages/server-wallet/src/wallet/__test__/integration/close-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/create-channel.test.ts
  packages/server-wallet/src/wallet/types.ts
  packages/server-wallet/src/wallet/wallet-response.ts
Labels: enhancement

#3259 refactor: ObjectiveModel.insert returns a DBObjective
  packages/server-wallet/src/models/objective.ts
  packages/server-wallet/src/wallet/store.ts
Labels: :broom: chore

#3267 Factor out common test setup in DefundChannel tests
  packages/server-wallet/src/protocols/__test__/defund-channel.test.ts
Labels: :memo: conventional

#3273 Add unit tests for channel model funding getters
  packages/server-wallet/src/models/__test__/channel.test.ts
Labels: :memo: conventional

#3272 refactor: ignore UniqueViolationError at the query level
  packages/server-wallet/package.json
  packages/server-wallet/src/models/objective.ts
  packages/server-wallet/src/wallet/store.ts
  yarn.lock
Labels: :broom: chore

#3245 chore: create spike template
  .github/ISSUE_TEMPLATE/spike.md
Labels: :broom: chore

#3280 DRY WorkerManager with a sendOperation method
  packages/server-wallet/src/wallet/multi-threaded-wallet/manager.ts
Labels: :broom: chore

#3275 Add SyncObjective method to Wallet
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/__test__/sync-objectives.test.ts
  packages/server-wallet/src/models/objective.ts
  packages/server-wallet/src/wallet/__test__/fixtures/open-channel-objective.ts
  packages/server-wallet/src/wallet/__test__/sync-objectives.test.ts
  packages/server-wallet/src/wallet/store.ts
  packages/server-wallet/src/wallet/wallet-response.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: :memo: conventional, enhancement

#3291 test: disable new objective check
  packages/server-wallet/src/__test__/sync-objectives.test.ts
Labels: :memo: conventional

#3288 feat: worker threads include threadId in log statements
  packages/server-wallet/src/wallet/multi-threaded-wallet/worker.ts
Labels: :memo: conventional, enhancement

#3293 refactor: change isDirectFunded parameter to be more verbose
  packages/server-wallet/src/models/channel.ts
Labels: :memo: conventional

#3284 docs: about type mismatches on insert()
  packages/server-wallet/src/models/objective.ts
Labels: :book: documentation, :memo: conventional

#3294 refactor: add an explicit type for funding milestones
  packages/server-wallet/src/models/__test__/channel.test.ts
  packages/server-wallet/src/models/channel.ts
  packages/server-wallet/src/protocols/direct-funder.ts
Labels: :memo: conventional

#3297 fix: do not assume that a ledger channel is directly funded
  packages/server-wallet/src/protocols/ledger-funder.ts
Labels: :memo: conventional

#3310 chore: introduce Cranker<> type
  packages/server-wallet/src/objectives/objective-manager.ts
  packages/server-wallet/src/protocols/challenge-submitter.ts
  packages/server-wallet/src/protocols/channel-closer.ts
  packages/server-wallet/src/protocols/channel-opener.ts
  packages/server-wallet/src/protocols/defund-channel.ts
Labels: :memo: conventional

#3305 chore: update PR template with zenhub pipeline definition
  .github/pull_request_template.md
Labels: :broom: chore, :memo: conventional

#3318 move "ledger channel patching" outside of ensureOpenChannelObjective
  packages/server-wallet/src/models/objective.ts
  packages/server-wallet/src/wallet/store.ts
Labels: :broom: chore

#3322 fix: do not use system user for postgres
  packages/server-wallet/package.json
  packages/server-wallet/src/db-admin/db-admin.ts
Labels: 🐛 bug

#3327 test: fix not waiting for an async operation
  packages/server-wallet/src/protocols/__test__/defunder.test.ts
Labels: :memo: conventional

#3324 Introduce check on chainId during store.addSignedState.
  packages/docs-website/docs/docs/protocol-tutorial/precautions-and-limits.md
  packages/server-wallet/src/config/defaults.ts
  packages/server-wallet/src/models/__test__/signing-wallet.test.ts
  packages/server-wallet/src/wallet/__test__/add-signed-state.test.ts
  packages/server-wallet/src/wallet/__test__/fixtures/states.ts
  packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts
  packages/server-wallet/src/wallet/__test__/fixtures/test-ledger-channel.ts
  packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts
  packages/server-wallet/src/wallet/store.ts
Labels: enhancement

#3315 refactor: remove ensureObjectives
  packages/server-wallet/e2e-test/e2e.test.ts
  packages/server-wallet/src/models/__test__/objectives.test.ts
  packages/server-wallet/src/models/objective.ts
  packages/server-wallet/src/objectives/close-channel.ts
  packages/server-wallet/src/objectives/objective-manager.ts
  packages/server-wallet/src/protocols/__test__/challenge-submitter.test.ts
  packages/server-wallet/src/protocols/__test__/close-channel.test.ts
  packages/server-wallet/src/protocols/__test__/defund-channel.test.ts
  packages/server-wallet/src/protocols/__test__/defunder.test.ts
  packages/server-wallet/src/protocols/defund-channel.ts
  packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts
  packages/server-wallet/src/wallet/__test__/fixtures/test-ledger-channel.ts
  packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts
  packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts
  packages/server-wallet/src/wallet/__test__/integration/update-funding.test.ts
  packages/server-wallet/src/wallet/__test__/sync-objectives.test.ts
  packages/server-wallet/src/wallet/store.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: 🧹 chore

#3328 pass chainId to the chain service
  packages/devtools/src/ganache/server.ts
  packages/server-wallet/e2e-test/challenge.test.ts
  packages/server-wallet/server-wallet.api.md
  packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts
  packages/server-wallet/src/chain-service/__chain-test__/stress.test.ts
  packages/server-wallet/src/chain-service/chain-service.ts
  packages/server-wallet/src/config/defaults.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: discussion, enhancement, 🧹 chore

#3333 test: DRY refactor of with-peers wallet tests
  packages/server-wallet/.vscode/launch.json
  packages/server-wallet/jest/jest.with-peers.config.js
  packages/server-wallet/jest/with-peers-setup-teardown.ts
  packages/server-wallet/package.json
  packages/server-wallet/src/__test__/with-peers/crash-tolerance/crash-tolerance.seqdiag
  packages/server-wallet/src/__test__/with-peers/crash-tolerance/crash-tolerance.test.ts
  packages/server-wallet/src/__test__/with-peers/create-and-close-channel/close-channel-simplified.seqdiag
  packages/server-wallet/src/__test__/with-peers/create-and-close-channel/direct-funding-simplified.seqdiag
  packages/server-wallet/src/__test__/with-peers/create-and-close-channel/direct-funding.test.ts
  packages/server-wallet/src/__test__/with-peers/create-and-close-channel/fake-funding-simplified.seqdiag
  packages/server-wallet/src/__test__/with-peers/create-and-close-channel/fake-funding.test.ts
  packages/server-wallet/src/__test__/with-peers/create-and-close-channel/ledger-funding.test.ts
  packages/server-wallet/src/__test__/with-peers/sync-objectives.test.ts
Labels: :memo: conventional, 🧹 chore

#3334 Add a chainService.checkChainId() and call during wallet creation
  packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts
  packages/server-wallet/src/chain-service/__chain-test__/stress.test.ts
  packages/server-wallet/src/chain-service/chain-service.ts
  packages/server-wallet/src/chain-service/mock-chain-service.ts
  packages/server-wallet/src/chain-service/types.ts
  packages/server-wallet/src/wallet/__test__/restarting.test.ts
  packages/server-wallet/src/wallet/wallet.ts
Labels: 🧹 chore

#3335 chore: clean up db names
  packages/server-wallet/jest/with-peers-setup-teardown.ts
  packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts
Labels: :memo: conventional, enhancement
